---
- name: Package boxfuse in docker images
  hosts: tag_group_builder
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - build
    - dockerhub

- name: Run application boxfuse from docker images
  hosts: tag_group_stage
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - stage
