---
- name: package boxfuse
  hosts: tag_group_builder
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - build
    - dockerhub

- name: Run application
  hosts: tag_group_stage
  remote_user: ubuntu
  become_user: root
  become: true
  roles:
    - stage
