---
- name: Install pip3
  apt:
    update_cache: yes
    name: python3-pip
  become: yes

- name: Install python docker sdk
  shell: |
    pip3 install docker
  become: yes

- name: Install docker
  apt:
    name: docker.io
  become: yes

- name: Start Docker
  shell: |
    systemctl start docker
    systemctl enable docker
  become: yes

- name: Install modules docker
  pip:
    name: "{{ item }}"
  with_items:
    - docker

- name: Add group
  group:
    name: docker
    state: present

- name: Add user to group
  user:
    name: ubuntu
    group: docker

- name: Create container
  docker_container:
    name: hello10
    image: kupa2004/hello:v1
    published_ports:
      - "8080:8080"
    state: started
